sudo: required
cache: bundler
language: ruby

services:
  - docker

before_install:
  - bundle install

env:
  matrix:
    - INSTANCE: postfix-debian-9
    - INSTANCE: postfix-ubuntu-1804
    - INSTANCE: postfix-centos-7
    - INSTANCE: postfix-fedora-latest

script:
  - bundle exec kitchen verify ${INSTANCE}

